### ISSUE TITLE
Summarization/Translation support

### ISSUE THREAD

**Issue by sshleifer** [wangcongcong123/ttt#1]
Cool lib!

I was wondering if it's possible tested to run translation finetuning with this library, for example on the `wmt_en_ro` data.

**Download Instructions**
```
wget https://s3.amazonaws.com/datasets.huggingface.co/translation/wmt_en_ro.tar.gz
tar -xzvf wmt_en_ro.tar.gz
```

Thanks and great work!

**Comment by wangcongcong123** [comment]
Yeah, I think that will not take much time to scale this lib to support translation task. At least for t5, it is straightforward. I will work on it and see how it's going.

**Comment by wangcongcong123** [comment]
Hi @sshleifer, I already added the translation task to this lib, details here: https://github.com/wangcongcong123/ttt#wmt_en_ro_t5

**Comment by sshleifer** [comment]
Super cool! Have you run it? Do you know scores/training time? If not I can just run it on my own at some point :)

**Comment by wangcongcong123** [comment]
On a TPUv3-8, the bleu score achieved by t5-base is 27.9 (very close to 28 as reported in [the T5 paper](https://arxiv.org/abs/1910.10683)), the fine-tuning args are [here](https://ucdcs-student.ucd.ie/~cwang/ttt/models/en2ro_t5_base/args.json) and training log is [here](https://ucdcs-student.ucd.ie/~cwang/ttt/models/en2ro_t5_base/train.log).

**Comment by sshleifer** [comment]
Wow! 90 Mins!
I assume for summarization you should just change args?
Will it work for any t5 checkpoint in the huggingface model hub?
