### ISSUE TITLE
Demo colab notebook error: "required positional argument: 'logger'"

### ISSUE THREAD

**Issue by SBrownAU** [wangcongcong123/ttt#3]
I noticed this error first in my own notebook, then was able to replicate in the colab notebook @ https://colab.research.google.com/github/wangcongcong123/ttt/blob/master/ttt_notebook.ipynb 

Following error is received when running:

```
     40   model, strategy = create_model(args, logger, get_model)
     41   # start training, here we customize T2TTrainer to get more control and flexibility
---> 42   trainer = T2TTrainer(args)
     43   trainer.train(model, strategy, tokenizer, inputs)

TypeError: __init__() missing 1 required positional argument: 'logger'
```

**Comment by wangcongcong123** [comment]
I have updated and now it should work.

**Comment by SBrownAU** [comment]
Thanks, I'm admittedly a novice at Python and Colab, however, I get further now, but still errors out:

![Selection_132](https://user-images.githubusercontent.com/4087047/103724175-9ac62680-5038-11eb-8a5c-004ef444f05d.png)

I'm also not sure it will work with latest (v4) transformers, see breaking changes @ https://github.com/huggingface/transformers/releases/tag/v4.0.0 specifically the need to now `use_fast=False`

**Comment by wangcongcong123** [comment]
This has not been fully tested with the latest transformers. I suggest you to try `pip install transformers==3.3.1`
